export const environment = {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY : 'CLERK_PUBLISHABLE_KEY',
    CLERK_SECRET_KEY : 'PASTE_YOUR_CLERK_SECRET_KEY_HERE',
    NEXT_PUBLIC_API_URL:'API_URL',
    NEXT_PUBLIC_WS_URL:'WS_URL',
}